inherit_gem:
  theforeman-rubocop:
    - strictest.yml

# TODO: remove this file by either moving cops here or fixing code
inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

Layout/LineLength:
  Exclude:
    - 'test/**/*.rb'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'test/**/*.rb'

Metrics/BlockLength:
  Max: 45
  Exclude:
    - 'config/*routes.rb'
    - 'lib/foreman_salt/plugin.rb'
    - 'test/**/*.rb'
