name: Rubocop
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
          bundler-cache: true
      - name: Setup rubocop
        run: |
          gem install bundler
      - name: Execute rubocop
        run: |
          bundle exec rubocop
